backend/api/urls.py
from django.urls import path
from api.views import (index, show_category)

app_name = 'api'

urlpatterns = [
    path('<int:user_id>/', index, name='home'),
    path('category/<int:user_id>/<str:cat_slug>/',  show_category, name='category'),
]

backend/backend/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('api/', include('api.urls', namespace='api')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('register/', include('tg_users.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

backend/basket/urls.py
from django.urls import path

from .views import basket_view, basket_add, basket_update, basket_delete, sendMessageOrderInTelegram
app_name = 'basket'

urlpatterns = [
    path('<int:user_id>/', basket_view, name='basket-view'),
    path('add/<int:user_id>/', basket_add, name='add-to-cart'),
    path('delete/<int:user_id>/', basket_delete, name='delete-to-cart'),
    path('update/<int:user_id>/', basket_update, name='update-to-cart'),
    path('message/<int:user_id>/', sendMessageOrderInTelegram, name='message'),
]

backend/api/forms.py
import random
import re
from django import forms
from tg_users.models import UserTelegram
from django.core.exceptions import ValidationError
from django.utils.deconstruct import deconstructible


@deconstructible
class RussianValidator:
    ALLOWED_CHAR = 'абвгдеёжзийклмнопрстуфхцчшщъыьэюя '
    code = 'russian'

    def __init__(self, message=None):
        self.message = message if message else "Должны присутствовать только русские буквы!"

    def __call__(self, value, *args, **kwargs):
        if not (set(value.lower()) <= set(self.ALLOWED_CHAR)):
            raise ValidationError(self.message, code=self.code)


class AddRegisterUserForm(forms.ModelForm):
    
    class Meta:
        model = UserTelegram
        fields = ['id', 'username', 'phone_user', 'date_of_birth']
        widgets = {
            'id': forms.HiddenInput(),
            'username': forms.TextInput(attrs={'class': 'form-control', 'name': 'name'}),
            'phone_user': forms.TextInput(attrs={'class': 'form-control'}),
            'date_of_birth': forms.TextInput(attrs={'class': 'form-control', 'type': 'date'}),
            }
        labels = {'username': 'Имя пользователя'}

    def clean_username(self):
        username = self.cleaned_data['username']
        if len(username) < 2:
            raise ValidationError("длина должна быть более 2 символов")
        if len(username) > 50:
            raise ValidationError("Длина имени превышает 50 символов")
        return username

    def clean_phone_user(self):
        user_phone = self.cleaned_data['phone_user']
        result = re.match(
            r'^(\+7|7|8)?[\s\-]?\(?[489][0-9]{2}\)?[\s\-]?[0-9]{3}[\s\-]?[0-9]{2}[\s\-]?[0-9]{2}$',
            string=user_phone)
        if not result:
            raise ValidationError("Данный номер телефона не соответствует")
        return user_phone

backend/api/views.py
from django.shortcuts import render, get_object_or_404
from catalog.models import Category, ProductProxy



def index(request, user_id):
    """
    Вывод главной страницы
    """
    post = ProductProxy.published.filter(is_published=1)
    data = {
        'title': 'Главная страница',
        'posts': post,
        'cat_selected': 0,
        'counter': 1,
        'user_id': user_id
        
    }
    return render(request, 'api/index.html', context=data)


def show_category(request, user_id, cat_slug):
    """
    Вывод товара по категориям
    """
    print(user_id, cat_slug)
    category = get_object_or_404(Category, slug=cat_slug)
    posts = ProductProxy.published.filter(cats__id=category.pk)
    data = {
        'menu': category,
        'posts': posts,
        'cat_selected': category.pk,
        'cat_slug': cat_slug,
        'user_id': user_id
    }
    return render(request, 'api/index.html', context=data)

backend/api/templates/api/index.html
{% extends "base.html" %}
{% load static %}
{% load api_tags %}

{% block title%}{{ title }}{% endblock %}
{% block nav %} 
	{% show_categories user_id cat_selected%} 
{% endblock nav %}
{% block content %}
<section class="cards">
	<div class="container container_cards">
	{% load cache %}
	<!-- Карточка товара -->
	{% for item in posts%} 
		<div class="card" data-id="{{ item.pk }}">
		<!-- Верхняя часть -->
			<div class="card__top">
				<!-- Изображение-ссылка товара -->
				<a href="#" class="card__image">
				<img class="product-img" src="{{ item.image.url}}" alt="{{ item.name }}"/></a>
			</div>
			<!-- Нижняя часть -->
			<div class="card__bottom">
				<p class="card__title">{{item.name}}</p>
					

				<div class="details-wrapper" id="{{ item.pk }}">
					<div class="card__prices">
						<div class="card__price card__price--common">{{item.price|floatformat}}</div>
						<div class="card__price card__weight">{{item.weight}}</div>
					</div>
					<div class="items" id='counter-open' data-open-counter>
						<button class="items__control" data-action="minus">-</button>
						<div id="select" class="items__current" data-counter>{{ item.quantity }}</div>
						<button id="button_plus" class="items__control" data-action="plus">+</button>
					</div>
					<button id="add-button" data-cart class="button card__add" button__hidden>+</button>
					
				</div>
			</div>
		</div>
		{% endfor %}	
	<br>
	<br>
	<div class="d-grid gap-2 btn-cont" id="button_none">
        	<a href="{% url 'basket:basket-view' user_id %}" class="join_btn-api">Перейти в корзину</a>
	</div>
	<div class="usercard" id="usercard"></div>
</section>
</div>
<script src="{% static 'api/js/counter.js' %} "></script>
<script src="{% static 'api/js/counter__bascet.js' %} "></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script >
	window.addEventListener('click', function(event){
		const detailsWrapper = event.target.closest('.details-wrapper');
		const currentUrl = window.location.href
		console.log(currentUrl)
		if(event.target.hasAttribute('data-cart'))
		{
			$.ajax({
				type: 'POST',
				url: '{% url "basket:add-to-cart" user_id %}',
				data: {
					product_id: detailsWrapper.id,
					product_qty: detailsWrapper.querySelector('[data-counter]').innerText,
					current_url: currentUrl,
					csrfmiddlewaretoken: '{{ csrf_token }}',
					action: 'post'
				},
				success: function(response){
					return true
					
				},
				error: function(response){
					console.log(response);
				},
			})
		}
		if (event.target.dataset.action === 'plus' || event.target.dataset.action === 'minus'){
			if (event.target.dataset.action === 'plus'){
		
				$.ajax({
					type: 'POST',
					url: '{% url "basket:update-to-cart" user_id %}',
					data: {
						product_id: detailsWrapper.id,
						product_qty: detailsWrapper.querySelector('[data-counter]').innerText,
						csrfmiddlewaretoken: '{{ csrf_token }}',
						action: 'post'
					},
					success: function(response){
						return true
					},
					error: function(response){
						console.log(response);
					},
				})
			}
			if (event.target.dataset.action === 'minus'){
				let url = '';
				if (detailsWrapper.querySelector('[data-counter]').innerText > 1){
					url = '{% url "basket:update-to-cart" user_id %}'
				}
				else{
					url = '{% url "basket:delete-to-cart" user_id %}';
				}
				$.ajax({
					type: 'POST',
					url: url,
					data: {
						product_id: detailsWrapper.id,
						product_qty: detailsWrapper.querySelector('[data-counter]').innerText,
						csrfmiddlewaretoken: '{{ csrf_token }}',
						action: 'post'
					},
					success: function(response){
						return true
					},
					error: function(response){
						console.log(response);
					},
				})
			}
		}
	})
</script>
<script src="https://telegram.org/js/telegram-web-app.js"></script>
	<script>
		let tg = window.Telegram;

		if(tg != undefined){
			if (tg.WebApp != undefined && tg.WebApp.initData != undefined){
				tg.WebApp.expand();

			}
		}
	</script>
{% endblock content %}