backend/api/urls.py
from django.urls import path
from api.views import (index, show_category)

app_name = 'api'

urlpatterns = [
    path('<int:user_id>/', index, name='home'),
    path('category/<int:user_id>/<str:cat_slug>/',  show_category, name='category'),
]

backend/backend/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('api/', include('api.urls', namespace='api')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('register/', include('tg_users.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

backend/basket/urls.py
from django.urls import path

from .views import basket_view, basket_add, basket_update, basket_delete, sendMessageOrderInTelegram
app_name = 'basket'

urlpatterns = [
    path('<int:user_id>/', basket_view, name='basket-view'),
    path('add/<int:user_id>/', basket_add, name='add-to-cart'),
    path('delete/<int:user_id>/', basket_delete, name='delete-to-cart'),
    path('update/<int:user_id>/', basket_update, name='update-to-cart'),
    path('message/<int:user_id>/', sendMessageOrderInTelegram, name='message'),
]

backend/basket/models.py
from django.db import models

from catalog.models import Catalog
from tg_users.models import UserTelegram

# Create your models here.
class Basket(models.Model):
    user = models.ForeignKey(UserTelegram, on_delete=models.CASCADE)
    product = models.ForeignKey(Catalog, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзина'
        ordering = ('id',)

    def __str__(self) -> str:
        return f'Корзина для {self.user.user} | Продукты {self.product.name}'

backend/basket/views.py
import requests
from django.shortcuts import render, get_object_or_404
from django.conf import settings
from django.http import JsonResponse, HttpResponseRedirect


from .cart import Cart
from catalog.models import ProductProxy
from tg_users.models import UserTelegram

# Create your views here.

def basket_view(request, user_id):
    cart = Cart(request)
    context = {
        'cart': cart,
        'user_id': user_id,
    }
    return render(request, 'basket/basket-view.html', context)


def basket_add(request, user_id):
    cart = Cart(request)

    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('product_id'))
        product_qty = int(request.POST.get('product_qty'))
        product = get_object_or_404(ProductProxy, id=product_id)
        cart.add(product=product, quantity=product_qty)

        cart_qty = cart.__len__()
        response = JsonResponse({'qty': cart_qty, 'product': product.name, 'user_id': user_id})

        return response
    print("Error")


def basket_delete(request, user_id):
    cart = Cart(request)

    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('product_id'))
        cart.delete(product=product_id)
        cart_qty = cart.__len__()
        cart_total = cart.get_total_price()
        response = JsonResponse({'qty': cart_qty, 'total': cart_total, 'user_id': user_id})
        return response


def basket_update(request, user_id):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('product_id'))

        product_qty = int(request.POST.get('product_qty'))
        cart.update(product=product_id, quantity=product_qty)

        cart_qty = cart.__len__()
        cart_total = cart.get_total_price()
        response = JsonResponse({'qty': cart_qty, 'total': cart_total, 'user_id': user_id})
        return response


def sendMessageOrderInTelegram(request, user_id):
    cart = Cart(request)
    user = get_object_or_404(UserTelegram, id=user_id)
    messageInTGBOT = cart.sendMessage()
    URI_API = settings.URI_API
    params = {
        'chat_id': user_id,
        'text': messageInTGBOT,
        'parse_mode': 'html',

    }
    requests.get(URI_API, params=params)
    messageInTGBOT += f'Имя пользователя: <b>{user.username}</b>\nНомер телефона: <b>{user.phone_user}</b>'
    CHAT_ID = settings.CHAT_ID_ORDERS
    params = {
        'chat_id': CHAT_ID,
        'text': messageInTGBOT,
        'parse_mode': 'html',
    }

    requests.get(URI_API, params=params)
    cart.clean_users_session()
    message = "Ваш заказ успешно сформирован, ожидайте звонка оператора!Заказ в боте продублирован!Хорошего дня"
    context = {
	'cart': cart,
        'user_id': user_id,
	'message': message,
    }
    return render(request, 'basket/basket-view.html', context)

backend/basket/templates/basket/basket-view.html
{% extends 'cart_base.html'%}
{% block content %}
{% load static %}
{% load mathfilters %}


<section class="section-cart">
    <div class="container">
        <div class="header_cart">
            <a href="{% url 'api:home' user_id  %}"><img src="{% static 'basket/img/icons/back.svg'%}" class="product__img-header"  alt=""></a>
            <h1 class="title-1">Ваш заказ</h1>
        </div>
    </div>
	{% if message %}
            <div class="alert alert-success" role="alert">
                <h4 class="alert-heading"><p class="text-justify">Спасибо за заказ!</p></h4>
                <p>{{ message }}</p>
            </div>
        {% else %}
        <div class="section-cart__body">
            <div class="container">
                <section class="cart">
                    <header class="cart-header">
                        <div class="cart-header__title">Наименование</div>
                        <div class="cart-header__count">Количество</div>
                        <div class="cart-header__cost">Стоимость</div>
                    </header>
                    {% if cart %}
                        {% for item in cart %}
                            {% with product=item.product %}
                                <section class="product" id="{{ product.id }}">
                                    <div class="product__img">
                                        <img src="{{ product.image.url }}"  alt="">
                                    </div>
                                    <div class="product__title">{{ product.name }}</div>
                                    <div class="product__controls" data-index="{{ product.id }}">
                                        <button type="button" class="delete-button">
                                            <img src="{% static 'basket/img/icons/x.svg'%}" alt="Delete" data-action="delete-cart">
                                        </button>
                                    </div>
                                    <div class="count__controls" data-index="{{product.id}}">
                                        <div class="items" id='counter-open' data-open-counter>
                                            <button class="items__control" data-action="minus_cart">-</button>
                                            <div id="select" class="items__current" data-counter-cart>{{item.qty}}</div>
                                            <button id="button_plus" class="items__control" data-action="plus_cart">+</button>
                                        </div>
                                    </div>
                                    <div class="product__price">{{ product.price }}</div>
                                </section>
                            {% endwith %}
                        {% endfor %}
                    {% else %}
                        <div class="empty-carts">
                            <p class="emppty-carts__text">Ваша корзина пуста</p>
                        </div>
                    {% endif %}
                    <footer class="cart-footer">
                        <div class="cart-footer__count">Всего:</div>
                        <div class="cart-footer__price" id="total">{{ cart.get_total_price }} руб.</div>
                    </footer>
                    <br>
        	    <br>
		    <div class="btn-cont" id="button_none" data-index="{{product.id}}"><a href="{% url 'basket:message' user_id %}" data-action="complete_order_cart">Оформить заказ</a></div>
		</section>
            </div>
        </div>
	{% endif %}
</section>
<script src="https://telegram.org/js/telegram-web-app.js"></script>
<script src="{% static 'basket/js/add_cart_complete.js'%}"></script>
<script src="{% static 'basket/js/counter_basket.js'%}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script >
	window.addEventListener('click', function(event){
        if (event.target.dataset.action === 'delete-cart'){
            const counterWrapper = event.target.closest('.product__controls');
            console.log(counterWrapper.dataset.index)
            $.ajax({
				type: 'POST',
				url: '{% url "basket:delete-to-cart" user_id %}',
				data: {
					product_id: counterWrapper.dataset.index,
					
					csrfmiddlewaretoken: '{{ csrf_token }}',
					action: 'post'
				},
				success: function(response){
					// qty_update.value = response.qty;
                    location.reload();
                    console.log(response);
					
				},
				error: function(response){
					console.log(response);
				},
			})
        }
        if (event.target.dataset.action === 'plus_cart' || event.target.dataset.action === 'minus_cart'){
            // const btn_hidden = event.target.closest('.button')
		    const counterWrapper = event.target.closest('.count__controls');
		    // Находим div с числом счетчика
		    const counter = counterWrapper.querySelector('[data-counter-cart]');
            if (event.target.dataset.action === 'plus_cart'){
                console.log(counter)
                $.ajax({
                    type: 'POST',
                    url: '{% url "basket:update-to-cart" user_id %}',
                    data: {
                        product_id: counterWrapper.dataset.index,
                        product_qty: counter.innerText,
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                        action: 'post'
                    },
                    success: function(response){
                        location.reload()
                        console.log(response);
                        
                    },
                    error: function(response){
                        console.log(response);
                    },
                })
            }
            if (event.target.dataset.action === 'minus_cart'){
                if (parseInt(counter.innerText) > 0){
                    $.ajax({
                        type: 'POST',
                        url: '{% url "basket:update-to-cart" user_id %}',
                        data: {
                            product_id: counterWrapper.dataset.index,
                            product_qty: counter.innerText,
                            csrfmiddlewaretoken: '{{ csrf_token }}',
                            action: 'post'
                        },
                        success: function(response){
                            location.reload()
                            console.log(response);
                            
                        },
                        error: function(response){
                            console.log(response);
                        },
                    })
                }
            }
        }
	})
</script>
{% endblock content%}